# Generated by Django 5.0.4 on 2024-04-24 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('DOCTOR_ID', models.AutoField(primary_key=True, serialize=False)),
                ('DOCTOR_NAME', models.CharField(max_length=100)),
                ('DOCTOR_SPECIALIZATION', models.CharField(max_length=100)),
                ('DOCTOR_CONTACT', models.BigIntegerField()),
                ('DOCTOR_SCHEDULE', models.TextField()),
                ('DOCTOR_UNIT', models.CharField(max_length=100)),
                ('DOCTOR_QUALIFICATION', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('PATIENT_ID', models.AutoField(primary_key=True, serialize=False)),
                ('PATIENT_NAME', models.CharField(max_length=100)),
                ('PATIENT_GENDER', models.CharField(max_length=10)),
                ('PATIENT_DOB', models.DateField()),
                ('PATIENT_CONTACT', models.BigIntegerField()),
                ('PATIENT_ADDRESS', models.TextField()),
                ('PATIENT_HISTORY', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('APPOINTMENT_ID', models.AutoField(primary_key=True, serialize=False)),
                ('APPOINTMENT_DATE', models.DateField()),
                ('APPOINTMENT_STATUS', models.CharField(max_length=100)),
                ('DOCTOR_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.doctor')),
                ('PATIENT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.patient')),
            ],
        ),
    ]
