# Generated by Django 5.0.4 on 2024-04-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='DOCTOR_ID',
            field=models.CharField(max_length=100),

        ),
        migrations.AlterField(
            model_name='appointment',
            name='PATIENT_ID',
            field=models.CharField(max_length=100),
        ),
    ]
